[package]
name = "notes"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "notes"

[dependencies]
hdk = { workspace = true }

serde = { workspace = true }

notes_integrity = { path = "../../integrity/notes", package = "notes_integrity" }
